### ISSUE TITLE
Did you need hire more engineers?

### ISSUE THREAD

**Issue by netroby** [HunanTV/eru-core#1]
Did you need hire more engineers?
Hunan TV is the best loved channel of my wife.

**Comment by CMGS** [comment]
Yes,
which position you want？

On Sat, Mar 14, 2015 at 6:09 AM, netroby <notifications@github.com> wrote:

> Did you need hire more engineers?
> Hunan TV is the best loved channel of my wife.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HunanTV/eru-core/issues/1>.
>



-- 

-CMGS
A simple coder.
Love travel, sports especially outdoor sports and computer technology.
Have a dream that one day can tour around.

**Comment by netroby** [comment]
Dev/OPS/DevOPS. interest in Cloud Computing tech and relates stuff.
