### ISSUE TITLE
Seems the mission of this project close to Kubernetes

### ISSUE THREAD

**Issue by netroby** [HunanTV/eru-core#2]
Seems the mission of this project close to Kubernetes

https://github.com/googlecloudplatform/kubernetes

Manage containers/cluster, scale out.... etc.

Seem you guys reinvent a new wheel

**Comment by netroby** [comment]
That's fine, may be your wheel better than others.

**Comment by CMGS** [comment]
This project aims to borg system, so does Kubernetes. That’s why they have something in common. The project Kubernetes started at the same time as I started my project. And it was unstable that time. So I decided to continue my development.

**Comment by netroby** [comment]
Good jobs. continue your job. but i guess your development progress will hard. No enough developers will cause the projects delay or hang up.
